# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchclock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='projects_shared', to='punchclock.Puncher'),
        ),
    ]
