# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punchclock', '0004_auto_20161123_1524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puncher',
            new_name='Profile',
        ),
    ]
